# Generated by Django 5.1.1 on 2024-10-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('sch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'school',
                'managed': False,
            },
        ),
    ]
