# Generated by Django 5.1.1 on 2024-10-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("octopus", "0002_school"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("answer_id", models.IntegerField(primary_key=True, serialize=False)),
                ("Answers", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "answer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Assess",
            fields=[
                ("assess_id", models.IntegerField(primary_key=True, serialize=False)),
                ("assess_area", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "assess",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                ("award_id", models.IntegerField(primary_key=True, serialize=False)),
                ("award", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "award",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                ("class_id", models.IntegerField(primary_key=True, serialize=False)),
                ("class_name", models.CharField(db_column="Class", max_length=255)),
            ],
            options={
                "db_table": "class",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("std_id", models.IntegerField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "student",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("subj_id", models.IntegerField(primary_key=True, serialize=False)),
                ("subject_name", models.CharField(db_column="Subject", max_length=255)),
            ],
            options={
                "db_table": "subject",
                "managed": False,
            },
        ),
    ]
