version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=assessment.settings
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: defaultdb
      MYSQL_USER: avnadmin
      MYSQL_PASSWORD: AVNS__C9FKK7Q-EONQ87AQFi
      MYSQL_ROOT_PASSWORD: AVNS__C9FKK7Q-EONQ87AQFi
    ports:
      - "3307:3306"
